version: '3'

services:
  postgres:
    container_name: garciasdos_postgres
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=manhattan
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 54355:5432

  nginx:
    container_name: garciasdos_nginx
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8030:80"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    container_name: garciasdos_php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9090:9001"
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    depends_on:
      - postgres
