imports:
  - { resource: ../../../../src/Mooc/Shared/Infrastructure/Symfony/DependencyInjection/mooc_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true

  # Configure
  _instanceof:
    Garciasdos\Shared\Domain\Bus\Event\DomainEventSubscriber:
      tags: ['codely.domain_event_subscriber']

    Garciasdos\Shared\Domain\Bus\Command\CommandHandler:
      tags: ['codely.command_handler']

    Garciasdos\Shared\Domain\Bus\Query\QueryHandler:
      tags: ['codely.query_handler']

  Garciasdos\Apps\Mooc\Backend\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  Garciasdos\Apps\Mooc\Backend\Command\:
    resource: '../src/Command'
    tags: ['console.command']

  # Wire
  Garciasdos\Shared\:
    resource: '../../../../src/Shared'

  Garciasdos\Mooc\:
    resource: '../../../../src/Mooc'

  # -- TAGGING --
  Garciasdos\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
    arguments: [!tagged codely.domain_event_subscriber]
    lazy: true

  Garciasdos\Shared\Infrastructure\Bus\Event\DomainEventMapping:
    arguments: [!tagged codely.domain_event_subscriber]

  Garciasdos\Shared\Infrastructure\Bus\Event\DomainEventSubscriberLocator:
    arguments: [!tagged codely.domain_event_subscriber]

  Garciasdos\Shared\Infrastructure\Doctrine\DatabaseConnections:
    arguments: [!tagged codely.database_connection]

  Garciasdos\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  Garciasdos\Shared\Infrastructure\Symfony\ApiExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onException }


  # -- APP DEFINITIONS --
  # Command/Query Handlers
  Garciasdos\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus:
    arguments: [!tagged codely.command_handler]

  Garciasdos\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus:
    arguments: [!tagged codely.query_handler]
